name: docker-compose-actions-workflow
on:
  push:
    branches:
      - 'development'
jobs:
  docker:
    environment: deployment-secrets
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v2
      -
        name: Checkout submodules
        run: git submodule update --init --recursive
      -
        name: Build doubtfire-web (create dist/)
        working-directory: ./doubtfire-web
        run: npm run-script deploy
      -
        name: Start containers
        run: docker compose -f "docker-compose.yml" up -d --build
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: user/app:latest
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}