name: docker-compose-actions-workflow
on:
  push:
    branches:
      - 'development'
jobs:
  docker:
    environment: deployment-secrets
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v2
      -
        name: Checkout submodules
        run: git submodule update --init --recursive
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./doubtfire-web
          push: false
          tags: doubtfire-web:latest
      -
        uses: addnab/docker-run-action@v3
        with:
          image: doubtfire-web:latest
          options: -v ${{ github.workspace }}/doubtfire-web:/doubtfire-web -v ${{ github.workspace }}/doubtfire-web/dist:/doubtfire-web/dist
          run: npm install
      -
        uses: addnab/docker-run-action@v3
        with:
          image: doubtfire-web:latest
          options: -v ${{ github.workspace }}/doubtfire-web:/doubtfire-web -v ${{ github.workspace }}/doubtfire-web/dist:/doubtfire-web/dist
          run: npm run-script deploy
      -
        name: Start containers
        run: docker-compose build -f "docker-compose.yml"
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./doubtfire-web
          push: true
          tags: doubtfire-web:latest
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}